# Generated by Django 6.0.5 on 2026-05-14 10:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام واحد تجاری')),
                ('logo', models.ImageField(upload_to='branding/logos/', verbose_name='لوگو')),
                ('signature', models.ImageField(upload_to='branding/signatures/', verbose_name='تصویر امضا/مهر')),
                ('primary_color', models.CharField(default='#a855f7', max_length=7, verbose_name='رنگ اصلی (HEX)')),
                ('invoice_header', models.ImageField(blank=True, null=True, upload_to='branding/headers/', verbose_name='تصویر سربرگ فاکتور')),
                ('address', models.TextField(blank=True, verbose_name='آدرس واحد')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='project_assets/%Y/%m/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فایل پروژه',
                'verbose_name_plural': 'فایل\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان وظیفه')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'فوری')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('due_date', models.DateField(verbose_name='فرصت انجام')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('businesses', models.ManyToManyField(blank=True, related_name='users', to='core.businessunit')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, help_text='درصد سهم (مثلا ۳۳.۳)', max_digits=5, verbose_name='درصد شراکت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شریک',
                'verbose_name_plural': 'شرکا',
            },
        ),
        migrations.CreateModel(
            name='PartnerRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ سهم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice', verbose_name='فاکتور')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='شریک')),
            ],
            options={
                'verbose_name': 'سهم سود شریک',
                'verbose_name_plural': 'سهم سود شرکا',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('deadline', models.DateField(verbose_name='مهلت نهایی')),
                ('total_budget', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بودجه کل (درآمد)')),
                ('total_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع هزینه\u200cها')),
                ('status', models.CharField(choices=[('PLANNING', 'در حال برنامه\u200cریزی'), ('ACTIVE', 'فعال'), ('COMPLETED', 'تکمیل شده')], default='PLANNING', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در نمونه\u200cکارها')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر اصلی نمونه\u200cکار')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessunit', verbose_name='واحد تجاری')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
    ]
