# Generated by Django 6.0.5 on 2026-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فاکتور')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تسویه شده')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('SENT', 'ارسال شده'), ('PAID', 'پرداخت شده'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت پرداخت')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح خدمات/کالا')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد/مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تراکنش')),
                ('type', models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=15, verbose_name='وضعیت')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transactions/', verbose_name='پیوست')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
            },
        ),
    ]
