# Generated by Django 6.0.5 on 2026-05-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد دوره')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دوره\u200cهای آموزشی',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('payment_status', models.CharField(choices=[('paid', 'تسویه کامل'), ('installment', 'اقساطی'), ('unpaid', 'بدهکار/بدون پرداخت')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل شهریه (تومان)')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده (تومان)')),
                ('avatar_3x4', models.ImageField(blank=True, null=True, upload_to='students/avatars/', verbose_name='عکس ۳*۴')),
                ('national_card_img', models.ImageField(blank=True, null=True, upload_to='students/documents/', verbose_name='عکس کارت ملی')),
                ('identity_img', models.ImageField(blank=True, null=True, upload_to='students/documents/', verbose_name='عکس شناسنامه')),
                ('is_documents_approved', models.BooleanField(default=False, verbose_name='تأیید اصالت مدارک')),
                ('short_slug', models.SlugField(blank=True, max_length=10, unique=True, verbose_name='لینک کوتاه پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'هنرجو',
                'verbose_name_plural': 'مدیریت هنرجویان',
            },
        ),
    ]
