# Generated by Django 6.0.5 on 2026-05-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardGenerator',
            fields=[
            ],
            options={
                'verbose_name': 'کارت شناسایی هنرجو',
                'verbose_name_plural': 'صدور و چاپ کارت شناسایی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.studentenrollment',),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
            ],
            options={
                'verbose_name': 'تأیید مدرک هنرجو',
                'verbose_name_plural': 'تأیید مدارک ارسالی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.studentenrollment',),
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('paid', 'تسویه کامل'), ('installment', 'اقساطی'), ('unpaid', 'بدهکار/بدون پرداخت')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل شهریه (تومان)')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده (تومان)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام در دوره')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_enrollments', to='academy.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_enrollments', to='academy.studentenrollment', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'جزئیات ثبت\u200cنام دوره',
                'verbose_name_plural': 'جزئیات ثبت\u200cنام دوره\u200cها',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
            ],
            options={
                'verbose_name': 'وضعیت مالی شهریه',
                'verbose_name_plural': 'وضعیت پرداخت اقساط/شهریه',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.courseenrollment',),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='academy.CourseEnrollment', to='academy.course', verbose_name='دوره\u200cها'),
        ),
    ]
