# Generated by Django 6.0.5 on 2026-05-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_idcardgenerator_studentdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید قسط')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت قسط')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت واقعی')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='academy.courseenrollment', verbose_name='ثبت\u200cنام مربوطه')),
            ],
            options={
                'verbose_name': 'قسط شهریه',
                'verbose_name_plural': 'اقساط شهریه هنرجویان',
            },
        ),
    ]
