# Generated by Django 6.0.5 on 2026-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academyinstallment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(max_length=11, verbose_name='شماره گیرنده')),
                ('message', models.TextField(verbose_name='متن پیامک')),
                ('sms_type', models.CharField(choices=[('profile_link', 'لینک پروفایل'), ('bulk_plain', 'ارسال دسته\u200cجمعی سفارشی'), ('installment_reminder', 'یادآوری اقساط')], max_length=30, verbose_name='نوع پیامک')),
                ('is_sent', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'گزارشات و لاگ پیامک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
