# Generated by Django 6.0.5 on 2026-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='document_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('verified', 'تأیید شده'), ('rejected', 'نقص مدارک')], default='pending', max_length=20, verbose_name='وضعیت مدارک'),
        ),
    ]
