# Generated by Django 6.0.5 on 2026-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_studentenrollment_document_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academyinstallment',
            options={'ordering': ['due_date'], 'verbose_name': 'قسط شهریه', 'verbose_name_plural': 'اقساط شهریه هنرجویان'},
        ),
        migrations.RemoveField(
            model_name='academyinstallment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='academyinstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('overdue', 'معوقه / گذشته از سررسید')], default='pending', max_length=20, verbose_name='وضعیت قسط'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی / یکجا'), ('installment', 'اقساطی'), ('unpaid', 'بدهکار / بدون پرداخت')], default='unpaid', max_length=20, verbose_name='نوع / وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='document_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت رد و نقص مدارک'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='is_documents_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید اصالت مدارک (منسوخ - ترجیحاً از document_status استفاده شود)'),
        ),
    ]
