# Generated by Django 6.0.5 on 2026-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_academyinstallment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق محل سکونت'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='education_level',
            field=models.CharField(blank=True, choices=[('under_diploma', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=30, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس اضطراری (والدین/همسر)'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='is_documents_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید اصالت مدارک'),
        ),
    ]
