# Generated by Django 6.0.5 on 2026-05-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_session_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'verbose_name': 'ثبت\u200cنام دوره', 'verbose_name_plural': 'جزئیات ثبت\u200cنام دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ پیامک', 'verbose_name_plural': 'گزارشات لاگ پیامک\u200cها'},
        ),
        migrations.AlterField(
            model_name='academyinstallment',
            name='due_date',
            field=models.DateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='academyinstallment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='academy.courseenrollment', verbose_name='ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='academyinstallment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='academyinstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('overdue', 'معوقه')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی / یکجا'), ('installment', 'اقساطی'), ('unpaid', 'بدهکار / بدون پرداخت')], default='unpaid', max_length=20, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل (تومان)'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='avatar_3x4',
            field=models.ImageField(blank=True, null=True, upload_to='students/avatars/', verbose_name='عکس ۳×۴'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='document_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت رد مدارک'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره اضطراری'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='identity_img',
            field=models.ImageField(blank=True, null=True, upload_to='students/documents/', verbose_name='شناسنامه'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='is_documents_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید مدارک'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='national_card_img',
            field=models.ImageField(blank=True, null=True, upload_to='students/documents/', verbose_name='کارت ملی'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='short_slug',
            field=models.SlugField(blank=True, max_length=10, unique=True, verbose_name='لینک کوتاه'),
        ),
    ]
