# Generated by Django 6.0.5 on 2026-06-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_courseenrollment_options_alter_smslog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, unique=True, verbose_name='شماره کارت')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='idcards/', verbose_name='QR Code')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کارت شناسایی',
                'verbose_name_plural': 'کارت\u200cهای شناسایی هنرجویان',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='تصویر دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.PositiveIntegerField(default=0, verbose_name='شهریه (تومان)'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=20, verbose_name='حداکثر ظرفیت'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_courses', to='academy.course', verbose_name='پیش\u200cنیاز'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('upcoming', 'به\u200cزودی'), ('open', 'ثبت\u200cنام باز'), ('full', 'تکمیل ظرفیت'), ('active', 'در حال برگزاری'), ('completed', 'پایان یافته')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
    ]
