# Generated by Django 6.0.5 on 2026-06-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_studentidcard_course_cover_image_course_fee_and_more'),
        ('users', '0002_alter_user_role_studentaccount_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.teacher', verbose_name='استاد دوره'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(choices=[('registration', 'تأیید ثبت\u200cنام'), ('payment', 'تأیید پرداخت'), ('document_approved', 'تأیید مدارک'), ('document_rejected', 'رد مدارک'), ('attendance_absent', 'اطلاع غیبت'), ('installment_reminder', 'یادآوری قسط'), ('course_start', 'شروع دوره'), ('bulk_plain', 'ارسال دسته\u200cجمعی'), ('template', 'پیامک الگو'), ('profile_link', 'لینک پروفایل')], max_length=30, verbose_name='نوع پیامک'),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='academy.studentenrollment', verbose_name='هنرجو'),
        ),
    ]
