# Generated by Django 6.0.5 on 2026-06-08 07:01

import apps.academy.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_course_teacher_alter_smslog_sms_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_public_registration',
            field=models.BooleanField(default=False, verbose_name='ثبت\u200cنام آنلاین'),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_slug',
            field=models.CharField(default=apps.academy.models.course._default_reg_slug, help_text='این کد در URL ثبت\u200cنام آنلاین استفاده می\u200cشود', max_length=12, verbose_name='لینک ثبت\u200cنام عمومی'),
        ),
    ]
