# Generated by Django 6.0.5 on 2026-06-08 07:01

import apps.academy.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_course_allow_public_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_slug',
            field=models.CharField(default=apps.academy.models.course._default_reg_slug, help_text='این کد در URL ثبت\u200cنام آنلاین استفاده می\u200cشود', max_length=12, unique=True, verbose_name='لینک ثبت\u200cنام عمومی'),
        ),
    ]
