# Generated by Django 6.0.5 on 2026-06-14 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_alter_course_registration_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('exam_type', models.CharField(choices=[('quiz', 'آزمک'), ('midterm', 'میان\u200cترم'), ('final', 'پایان\u200cترم'), ('assignment', 'تکلیف'), ('placement', 'تعیین سطح')], default='quiz', max_length=20, verbose_name='نوع آزمون')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدت زمان (دقیقه)')),
                ('pass_score_percent', models.PositiveIntegerField(default=50, help_text='درصدی از نمره کل که قبولی محسوب می\u200cشود', verbose_name='درصد قبولی')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='جابجایی تصادفی سوالات')),
                ('shuffle_choices', models.BooleanField(default=True, verbose_name='جابجایی تصادفی گزینه\u200cها')),
                ('show_result_immediately', models.BooleanField(default=False, verbose_name='نمایش نتیجه بلافاصله پس از آزمون')),
                ('show_answers_after', models.BooleanField(default=False, verbose_name='نمایش پاسخ\u200cهای صحیح پس از آزمون')),
                ('attempts_allowed', models.PositiveIntegerField(default=1, verbose_name='تعداد دفعات مجاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('random_question_count', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد، همه سوالات نمایش داده می\u200cشوند', null=True, verbose_name='تعداد سوال تصادفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academy.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('submitted', 'ارسال شده'), ('graded', 'تصحیح شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='حداکثر نمره')),
                ('is_passed', models.BooleanField(default=False, verbose_name='قبول شده')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='شماره تلاش')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی پی')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر')),
                ('is_cheating_suspected', models.BooleanField(default=False, verbose_name='مشکوک به تقلب')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.exam', verbose_name='آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='academy.studentenrollment', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'تلاش آزمون',
                'verbose_name_plural': 'تلاش\u200cهای آزمون',
                'ordering': ['-start_time'],
                'unique_together': {('exam', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای (تک پاسخ)'), ('multiple_answer', 'چند گزینه\u200cای (چند پاسخ)'), ('true_false', 'صحیح / غلط'), ('short_answer', 'پاسخ کوتاه'), ('essay', 'توصیفی (تشریحی)'), ('matching', 'جورکردنی'), ('fill_blank', 'پر کردن جای خالی'), ('ordering', 'ترتیب\u200cدهی')], max_length=20, verbose_name='نوع سوال')),
                ('title', models.TextField(help_text='متن اصلی سوال را وارد کنید', verbose_name='متن سوال')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='نمره')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam/questions/', verbose_name='تصویر سوال')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('explanation', models.TextField(blank=True, help_text='پس از پاسخ، این توضیح به هنرجو نشان داده می\u200cشود', null=True, verbose_name='توضیح پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.exam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن آیتم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam/ordering/', verbose_name='تصویر آیتم')),
                ('correct_order', models.PositiveIntegerField(verbose_name='ترتیب صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='academy.question', verbose_name='سوال ترتیب\u200cدهی')),
            ],
            options={
                'verbose_name': 'آیتم ترتیب\u200cدهی',
                'verbose_name_plural': 'آیتم\u200cهای ترتیب\u200cدهی',
                'ordering': ['correct_order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(verbose_name='متن ستون راست')),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='exam/matching/', verbose_name='تصویر ستون راست')),
                ('right_text', models.TextField(verbose_name='متن ستون چپ (پاسخ)')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='exam/matching/', verbose_name='تصویر ستون چپ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='academy.question', verbose_name='سوال جورکردنی')),
            ],
            options={
                'verbose_name': 'جفت جورکردنی',
                'verbose_name_plural': 'جفت\u200cهای جورکردنی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='پاسخ صحیح')),
                ('acceptable_alternatives', models.TextField(blank=True, help_text='هر پاسخ در یک خط جدا', null=True, verbose_name='سایر پاسخ\u200cهای قابل قبول')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='شماره جای خالی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_answers', to='academy.question', verbose_name='سوال جای خالی')),
            ],
            options={
                'verbose_name': 'پاسخ جای خالی',
                'verbose_name_plural': 'پاسخ\u200cهای جای خالی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن گزینه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam/choices/', verbose_name='تصویر گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='academy.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('matching_answers', models.JSONField(blank=True, help_text='{"left_id": "right_id", ...}', null=True, verbose_name='پاسخ\u200cهای جورکردنی')),
                ('fill_blank_answers', models.JSONField(blank=True, help_text='{"blank_id": "answer_text", ...}', null=True, verbose_name='پاسخ\u200cهای جای خالی')),
                ('ordering_answers', models.JSONField(blank=True, help_text='[item_id, item_id, ...] به ترتیب', null=True, verbose_name='ترتیب قرار داده شده')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='exam/answers/', verbose_name='فایل پاسخ')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='صحیح است؟')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره کسب شده')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.examattempt', verbose_name='تلاش')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='تصحیح شده توسط')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='academy.question', verbose_name='سوال')),
                ('selected_choices', models.ManyToManyField(blank=True, to='academy.choice', verbose_name='گزینه\u200cهای انتخاب شده')),
            ],
            options={
                'verbose_name': 'پاسخ هنرجو',
                'verbose_name_plural': 'پاسخ\u200cهای هنرجویان',
            },
        ),
    ]
