# Generated by Django 6.0.5 on 2026-06-15 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_exam_examattempt_question_orderingitem_matchingpair_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی هزینه',
                'verbose_name_plural': 'دسته\u200cبندی هزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام درگاه/کارت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('account_holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='صاحب حساب')),
                ('gateway_type', models.CharField(choices=[('pos', 'کارت\u200cخوان'), ('gateway', 'درگاه پرداخت آنلاین'), ('card', 'کارت بانکی'), ('bank', 'حواله بانکی'), ('cash', 'وجه نقد')], default='pos', max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درگاه/حساب مالی',
                'verbose_name_plural': 'درگاه\u200cها و حساب\u200cهای مالی',
            },
        ),
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه'), ('teacher_payout', 'پرداخت به مدرس'), ('refund', 'استرداد'), ('transfer', 'انتقال بین حساب')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'کارت\u200cخوان'), ('gateway', 'درگاه آنلاین'), ('bank', 'حواله / پایا'), ('check', 'چک'), ('installment', 'قسط')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت (۴ رقم آخر)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره رسید / فیش')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='accounting/receipts/', verbose_name='تصویر رسید')),
                ('transaction_date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='academy.course', verbose_name='دوره')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='academy.courseenrollment', verbose_name='ثبت\u200cنام')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='academy.studentenrollment', verbose_name='هنرجو')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_transactions', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='academy.expensecategory', verbose_name='دسته هزینه')),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='academy.paymentgateway', verbose_name='درگاه / حساب')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'دفتر کل تراکنش\u200cهای مالی',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
