# Generated by Django 6.0.5 on 2026-06-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_expensecategory_paymentgateway_accountingtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('material_type', models.CharField(choices=[('assignment', 'تکلیف / تمرین'), ('video', 'فیلم آموزشی'), ('file', 'فایل ضمیمه'), ('link', 'لینک مفید'), ('source_code', 'سورس کد'), ('other', 'سایر')], default='file', max_length=20, verbose_name='نوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='فایل')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.course', verbose_name='دوره')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'محتوا / منبع آموزشی',
                'verbose_name_plural': 'محتوای آموزشی',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
