# Generated by Django 6.0.5 on 2026-06-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_sessionmaterial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school', verbose_name='آموزشگاه'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school', verbose_name='آموزشگاه'),
        ),
    ]
