# Generated by Django 6.0.5 on 2026-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_course_school_studentenrollment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه جلسه (اختیاری)'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کلاس آنلاین'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز جلسه (اختیاری)'),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_type',
            field=models.CharField(choices=[('none', 'بدون کلاس آنلاین'), ('jitsi', 'جیتسی (Jitsi Meet)'), ('google_meet', 'گوگل میت (Google Meet)'), ('zoom', 'زوم (Zoom)'), ('bigbluebutton', 'بیگ\u200cبلوباتن (BigBlueButton)'), ('custom', 'سایر (لینک دلخواه)')], default='none', max_length=20, verbose_name='نوع کلاس آنلاین'),
        ),
    ]
