# Generated by Django 6.0.5 on 2026-06-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_session_meeting_id_session_meeting_link_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='schools.school', verbose_name='آموزشگاه'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='schools.school', verbose_name='آموزشگاه'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='schools.school', verbose_name='آموزشگاه'),
        ),
    ]
