# Generated by Django 6.0.5 on 2026-06-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_expensecategory_school_paymentgateway_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد درگاه (PIN)'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تراکنش درگاه')),
                ('authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد ارجاع درگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت پرداخت\u200cکننده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='academy.courseenrollment', verbose_name='ثبت\u200cنام')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='academy.studentenrollment', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
