# Generated by Django 6.0.5 on 2026-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_paymentgateway_merchant_code_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل برگزاری'),
        ),
    ]
