# Generated by Django 6.0.5 on 2026-07-19 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentidcard',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور'),
        ),
    ]
