# Generated by Django 6.0.5 on 2026-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0023_alter_studentidcard_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="gateway_payment_id",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="شناسهٔ پرداخت در درگاه سان\u200cتک",
            ),
        ),
    ]
