# Generated by Django 6.0.5 on 2026-06-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_studentidcard_course_cover_image_course_fee_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'صاحب کسب\u200cوکار / مدیر کل'), ('PARTNER', 'شریک تجاری'), ('MANAGER_ACADEMY', 'مدیر آکادمی'), ('MANAGER_COMPANY', 'مدیر شرکت فنی'), ('TEACHER', 'استاد / مدرس'), ('STUDENT', 'هنرجو')], default='OWNER', max_length=20, verbose_name='نقش کاربری'),
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='academy.studentenrollment', verbose_name='پرونده هنرجو')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'حساب هنرجو',
                'verbose_name_plural': 'حساب\u200cهای هنرجویان',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('salary_per_session', models.PositiveIntegerField(default=0, verbose_name='دستمزد هر جلسه (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'مدیریت اساتید',
            },
        ),
    ]
