# Generated by Django 6.0.5 on 2026-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت بانکی'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا'),
        ),
    ]
