# Generated by Django 6.0.5 on 2026-06-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0010_studentidcard_course_cover_image_course_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('registered', 'ثبت\u200cنام اولیه'), ('enrolled', 'ثبت\u200cنام کامل'), ('lost', 'از دست رفته')], default='new', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('instagram', 'اینستاگرام'), ('referral', 'معرفی دوست'), ('phone', 'تماس تلفنی'), ('walk_in', 'مراجعه حضوری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='منبع')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پیگیری')),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='academy.studentenrollment', verbose_name='تبدیل به هنرجو')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='academy.course', verbose_name='دوره موردعلاقه')),
            ],
            options={
                'verbose_name': 'سرنخ فروش',
                'verbose_name_plural': 'مدیریت سرنخ\u200cها (CRM)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('sms', 'پیامک'), ('meeting', 'جلسه حضوری'), ('email', 'ایمیل'), ('note', 'یادداشت')], max_length=20, verbose_name='نوع فعالیت')),
                ('description', models.TextField(verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='سرنخ')),
            ],
            options={
                'verbose_name': 'فعالیت CRM',
                'verbose_name_plural': 'فعالیت\u200cهای CRM',
                'ordering': ['-created_at'],
            },
        ),
    ]
