# Generated by Django 6.0.5 on 2026-07-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('schools', '0002_school_add_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='schools.school', verbose_name='آموزشگاه'),
        ),
    ]
