# Generated by Django 6.0.5 on 2026-06-16 08:38

import apps.schools.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام آموزشگاه / مدرسه')),
                ('slug', models.SlugField(default=apps.schools.models._default_slug, unique=True, verbose_name='شناسه یکتا')),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='زیردامنه (مثال: my-school)')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='دامنه اختصاصی (مثال: my-school.com)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='schools/favicons/', verbose_name='فاوآیکون')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='رنگ اصلی (hex)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_schools', to=settings.AUTH_USER_MODEL, verbose_name='مدیر / مالک آموزشگاه')),
            ],
            options={
                'verbose_name': 'آموزشگاه',
                'verbose_name_plural': 'مدیریت آموزشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
