# Generated by Django 6.0.5 on 2026-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='آموزشگاه پیش\u200cفرض (صفحه لاگین)'),
        ),
    ]
