# Generated by Django 6.0.5 on 2026-06-05 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0011_course_teacher_alter_smslog_sms_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فرم')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='شناسه URL')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('requires_login', models.BooleanField(default=False, verbose_name='نیاز به ورود')),
                ('one_response_per_user', models.BooleanField(default=False, verbose_name='یک پاسخ در هر کاربر')),
                ('submit_message', models.TextField(default='پاسخ شما ثبت شد. ممنون از شما!', verbose_name='پیام پس از ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('linked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='academy.course', verbose_name='دوره مرتبط')),
            ],
            options={
                'verbose_name': 'فرم دینامیک',
                'verbose_name_plural': 'فرم\u200cهای دینامیک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن بلند'), ('number', 'عدد'), ('email', 'ایمیل'), ('phone', 'موبایل'), ('select', 'انتخاب از لیست'), ('radio', 'انتخاب تکی'), ('checkbox', 'چندانتخابی'), ('date', 'تاریخ'), ('file', 'بارگذاری فایل'), ('rating', 'امتیازدهی'), ('heading', 'عنوان / تیتر'), ('paragraph', 'متن توضیحی')], max_length=20, verbose_name='نوع فیلد')),
                ('label', models.CharField(max_length=200, verbose_name='برچسب')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='متن راهنما')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='متن کمکی')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('options', models.TextField(blank=True, help_text='گزینه\u200cها را با خط جدید جدا کنید (برای select، radio، checkbox)', verbose_name='گزینه\u200cها')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر طول')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='حداقل مقدار')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.dynamicform')),
            ],
            options={
                'verbose_name': 'فیلد فرم',
                'verbose_name_plural': 'فیلدهای فرم',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_builder.dynamicform')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ فرم',
                'verbose_name_plural': 'پاسخ\u200cهای فرم',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='پاسخ')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='form_uploads/', verbose_name='فایل')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_builder.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_builder.formsubmission')),
            ],
            options={
                'verbose_name': 'پاسخ فیلد',
                'verbose_name_plural': 'پاسخ\u200cهای فیلد',
            },
        ),
    ]
