# Generated by Django 6.0.5 on 2026-10-01 08:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='عنوان سال تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='سال تحصیلی فعال')),
            ],
            options={
                'verbose_name': 'سال تحصیلی',
                'verbose_name_plural': 'سال\u200cهای تحصیلی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='پایه تحصیلی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پایه تحصیلی',
                'verbose_name_plural': 'پایه\u200cهای تحصیلی',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل باید با ۰۹ شروع شود و ۱۱ رقم باشد.')], verbose_name='شماره موبایل')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ولی / سرپرست',
                'verbose_name_plural': 'اولیا و سرپرستان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مدرسه')),
                ('education_code', models.CharField(blank=True, max_length=50, verbose_name='کد آموزش و پرورش')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/profile/', verbose_name='لوگو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشخصات مدرسه',
                'verbose_name_plural': 'مشخصات مدرسه',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('girl', 'دختر'), ('boy', 'پسر')], max_length=5, verbose_name='جنسیت')),
                ('mobile_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل باید با ۰۹ شروع شود و ۱۱ رقم باشد.')], verbose_name='شماره موبایل دانش\u200cآموز')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school/students/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='رشته تحصیلی')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد رشته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('code', models.CharField(max_length=30, verbose_name='کد کلاس')),
                ('capacity', models.PositiveSmallIntegerField(default=30, verbose_name='ظرفیت')),
                ('gender', models.CharField(choices=[('girls', 'دخترانه'), ('boys', 'پسرانه'), ('coed', 'مختلط')], default='coed', max_length=10, verbose_name='جنسیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school_management.academicyear', verbose_name='سال تحصیلی')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school_management.gradelevel', verbose_name='پایه')),
                ('study_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school_management.studyfield', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['academic_year__start_date', 'grade_level__order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='شماره دانش\u200cآموزی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('transferred', 'منتقل شده'), ('graduated', 'فارغ\u200cالتحصیل'), ('withdrawn', 'انصراف داده')], default='active', max_length=12, verbose_name='وضعیت')),
                ('enrolled_at', models.DateField(verbose_name='تاریخ ثبت\u200cنام')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school_management.academicyear', verbose_name='سال تحصیلی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school_management.classroom', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_enrollments', to='school_management.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام تحصیلی',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای تحصیلی',
                'ordering': ['-academic_year__start_date', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='school_unique_student_enrollment_per_year')],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('guardian', 'سرپرست قانونی'), ('other', 'سایر')], max_length=10, verbose_name='نسبت')),
                ('is_primary', models.BooleanField(default=False, verbose_name='ولی اصلی')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='دریافت\u200cکننده اعلان\u200cها')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='school_management.guardian', verbose_name='ولی / سرپرست')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='school_management.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ارتباط دانش\u200cآموز و ولی',
                'verbose_name_plural': 'ارتباط دانش\u200cآموزان و اولیا',
                'constraints': [models.UniqueConstraint(fields=('student', 'guardian'), name='school_unique_student_guardian')],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='school_unique_classroom_code_per_year'),
        ),
    ]
