# Generated by Django 6.0.5 on 2026-10-01 08:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='schoolenrollment',
            name='enrolled_at',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
